dist: "xenial"
language: "python"
python:
    - "3.7"

services:
    - "docker"

install:
    - "pip install -r requirements.txt"

before_script:
    - "pylint *.py"
    - "pytest --verbose src/text_calculator.py"
    - "docker-compose up -d"
    - "docker container ls"

# Run the system tests to ensure the web server is functional
script:
    - "pytest --verbose test_system.py"

after_script:
    - "docker-compose down"
